name: "Terraform Deployment Dev"

on:
  pull_request:
    paths:
      - 'noe/dev/**/*.tf'
      - '.github/workflows/terraform-deploy.yaml' # to trigger when this file changes
    branches: [ main ]

  push:
    paths:
      - 'noe/dev/**/*.tf'
      - '.github/workflows/terraform-deploy.yaml'
    branches: [ main ]  
  workflow_dispatch:

jobs:
  tf-plan:
    name: "Call Plan Dev"
    if: ${{ github.event_name == 'pull_request' }}
    uses: clouddrove-sandbox/aks-cicd-aaplication/.github/workflows/terraform-tf-plan.yaml@master
    with:
      working_directory: noe/dev/
      terraform_version: "1.9.2"
      plan_command: terraform plan -out=tfplan
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      MODULE_GITHUB_TOKEN: ${{ secrets.MODULE_GITHUB_TOKEN }}
